const synonyms = {
    // General Synonyms
    boots: 'shoes',
    shoes: 'boots',
    sneaker: 'trainers',
    trainers: 'sneaker',
    sandal: 'flipflops',
    flipflops: 'sandal',
    loafer: 'slipons',
    slipons: 'loafer',
    highheels: 'stilettos',
    stilettos: 'highheels',
    flats: 'ballerinas',
    ballerinas: 'flats',
    clogs: 'mules',
    mules: 'clogs',
    wedges: 'platforms',
    platforms: 'wedges',
    moccasins: 'slippers',
    slippers: 'moccasins',
    brogues: 'oxfords',
    oxfords: 'brogues',
    derbys: 'oxfords',
    oxfords: 'derbys',
    trainers: 'runners',
    runners: 'trainers',

    // Child Synonyms
    child: 'children',
    children: 'child',
    toddlers: 'childs',
    kids: 'childs',
    child: 'kids',
    infant: 'baby',
    baby: 'infant',
    preschooler: 'toddler',
    toddler: 'preschooler',
    grade_schooler: 'young_child',
    young_child: 'grade_schooler',

    // Gender Synonyms
    men: 'male',
    male: 'men',
    women: 'female',
    female: 'women',
    boys: 'male_child',
    male_child: 'boys',
    girls: 'female_child',
    female_child: 'girls',
    ladies: 'women',
    women: 'ladies',
    gentleman: 'man',
    man: 'gentleman',
    lady: 'woman',
    woman: 'lady',

    // Shoe Material Synonyms
    leather: 'hide',
    hide: 'leather',
    suede: 'napped_leather',
    napped_leather: 'suede',
    fabric: 'cloth',
    cloth: 'fabric',
    synthetic: 'artificial',
    artificial: 'synthetic',
    canvas: 'cloth',
    mesh: 'netting',
    netting: 'mesh',

    // Style Synonyms
    formal: 'dress_shoes',
    dress_shoes: 'formal',
    casual: 'everyday',
    everyday: 'casual',
    athletic: 'sports',
    sports: 'athletic',
    hiking: 'trail_shoes',
    trail_shoes: 'hiking',
    running: 'runners',
    runners: 'running',
    walking: 'walking_shoes',
    walking_shoes: 'walking',

    // Brand Synonyms (sample)
    nike: 'nikes',
    nikes: 'nike',
    adidas: 'adidases',
    adidases: 'adidas',
    puma: 'pumas',
    pumas: 'puma',
    reebok: 'reeboks',
    reeboks: 'reebok',
    asics: 'asicses',
    asicses: 'asics',
    converse: 'converses',
    converses: 'converse',
    vans: 'vanses',
    vanses: 'vans',

    // Use Case Synonyms
    running: 'jogging',
    jogging: 'running',
    gym: 'workout',
    workout: 'gym',
    basketball: 'hoops',
    hoops: 'basketball',
    soccer: 'football',
    football: 'soccer',
    tennis: 'tennis_shoes',
    tennis_shoes: 'tennis',

    // Expand to include more synonyms
    slip: 'slide',
    slide: 'slip',
    buckle: 'fastener',
    fastener: 'buckle',
    lace: 'shoelace',
    shoelace: 'lace',
    velcro: 'hook_and_loop',
    hook_and_loop: 'velcro',
    waterproof: 'water_resistant',
    water_resistant: 'waterproof',
    breathable: 'ventilated',
    ventilated: 'breathable',
    durable: 'long_lasting',
    long_lasting: 'durable',
    lightweight: 'light',
    light: 'lightweight',
    comfortable: 'comfy',
    comfy: 'comfortable',
    stylish: 'fashionable',
    fashionable: 'stylish',

    // Add more as needed to reach at least 1000
};

module.exports = synonyms;
